### ISSUE TITLE
Use Display Rules in CC Messages Plugin

### ISSUE THREAD

**Issue by altitudems** [academydistrict20/notifications#102]

**Comment by Lukeharris30** [comment]
:rocket: Issue was released in [`v0.7.0`](https://github.com/academydistrict20/notifications/releases/tag/v0.7.0) :rocket:

**Comment by Lukeharris30** [comment]
:rocket: Issue was released in [`v0.7.0`](https://github.com/academydistrict20/notifications/releases/tag/v0.7.0) :rocket:
