### ISSUE TITLE
feat(plugins): support multi-word display rule terms

### ISSUE THREAD

**Issue by altitudems** [academydistrict20/notifications#105]

**Comment by Lukeharris30** [comment]
:rocket: Issue was released in [`v0.8.0`](https://github.com/academydistrict20/notifications/releases/tag/v0.8.0) :rocket:

**Comment by Lukeharris30** [comment]
:rocket: Issue was released in [`v0.8.0`](https://github.com/academydistrict20/notifications/releases/tag/v0.8.0) :rocket:

**Comment by Lukeharris30** [comment]
:rocket: Issue was released in [`v0.8.0`](https://github.com/academydistrict20/notifications/releases/tag/v0.8.0) :rocket:
