### ISSUE TITLE
Polling not working

### ISSUE THREAD

**Issue by altitudems** [academydistrict20/notifications#68]
The pollInterval option does not work.

**Comment by Lukeharris30** [comment]
:rocket: Issue was released in [`v0.6.1`](https://github.com/academydistrict20/notifications/releases/tag/v0.6.1) :rocket:

**Comment by Lukeharris30** [comment]
:rocket: Issue was released in [`v0.6.1`](https://github.com/academydistrict20/notifications/releases/tag/v0.6.1) :rocket:
