### ISSUE TITLE
Styling fixes for UI components

### ISSUE THREAD

**Issue by altitudems** [academydistrict20/notifications#85]
Here are a couple of styling issues noticed on the UI components:

- [ ] The styles for detail links should have better contrast and match better with different backgrounds
- [ ] It would be great if calls to action were more button-like
- [ ] The color of description text, should be closer to grey, instead of blue, to fit better with each style of notifications
- [ ] The pagination indicators don't have enough contrast on banner notifications
- [ ] Consider adding some sort of transition when the bell closes/opens
- [ ] The animation for banners is a bit jarring, and not consistent between left and right
- [ ] The animation for floating notifications is not consistent between left and right
- [ ] There could be more padding in notifications on larger devices

**Comment by Lukeharris30** [comment]
:rocket: Issue was released in [`v0.7.0`](https://github.com/academydistrict20/notifications/releases/tag/v0.7.0) :rocket:
